language: csharp
solution: Kontur.ImageTransformer.sln
install:
  - nuget restore Kontur.ImageTransformer.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Kontur.ImageTransformer.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ImageTransformerTests/bin/Release/netcoreapp2.1/MyProject.Tests.dll
