dist: xenial
mono: none
dotnet: 2.2.100
language: csharp
solution: Kontur.ImageTransformer.sln
addons:
  apt:
    packages:
     - libc6-dev
     - libgdiplus
script:
  - dotnet restore
  - dotnet test
